// Dados dos projetos (mock)
const projects = [
  {
    id: 1,
    name: "Alerta Rio",
    institution: "Prefeitura do Rio de Janeiro",
    area: "Hidrometeorológica",
    type: "Monitoramento",
    description:
      "Sistema de alerta de chuvas fortes e deslizamentos na cidade do Rio de Janeiro.",
    location: "Rio de Janeiro, RJ",
    url: "http://alertario.rio.rj.gov.br/",
    contact: "contato@alertario.rio.rj.gov.br",
    lastUpdate: "2024-01-20",
  },
  {
    id: 2,
    name: "Cemaden Educação",
    institution:
      "Centro Nacional de Monitoramento e Alertas de Desastres Naturais",
    area: "Educação",
    type: "Educação",
    description:
      "Plataforma de recursos educacionais sobre desastres naturais para escolas e comunidades.",
    location: "Nacional",
    url: "https://www.cemaden.gov.br/cemaden-educacao/",
    contact: "cemaden.educacao@gmail.com",
    lastUpdate: "2024-02-10",
  },
  {
    id: 3,
    name: "Defesa Civil de Minas Gerais",
    institution: "Governo de Minas Gerais",
    area: "Geológica",
    type: "Resposta",
    description: "Ações de resposta a emergências geológicas em Minas Gerais.",
    location: "Minas Gerais",
    url: "http://www.defesacivil.mg.gov.br/",
    contact: "defesacivil@mg.gov.br",
    lastUpdate: "2024-02-15",
  },
  {
    id: 4,
    name: "INPE Queimadas",
    institution: "Instituto Nacional de Pesquisas Espaciais",
    area: "Incêndios",
    type: "Monitoramento",
    description: "Monitoramento de focos de queimadas em tempo real no Brasil.",
    location: "Nacional",
    url: "http://queimadas.dgi.inpe.br/",
    contact: "queimadas@inpe.br",
    lastUpdate: "2024-02-20",
  },
  {
    id: 5,
    name: "Monitoramento de Barragens",
    institution: "Agência Nacional de Águas",
    area: "Tecnológica",
    type: "Monitoramento",
    description:
      "Sistema de monitoramento de segurança de barragens no Brasil.",
    location: "Nacional",
    url: "https://www.ana.gov.br/assuntos/seguranca-de-barragens",
    contact: "segurancadebarragens@ana.gov.br",
    lastUpdate: "2024-02-25",
  },
  {
    id: 6,
    name: "Projeto Escudo",
    institution: "Prefeitura de Santos",
    area: "Tecnológica",
    type: "Alerta",
    description:
      "Sistema de monitoramento e alerta de riscos climáticos em Santos.",
    location: "São Paulo",
    url: "https://www.santos.sp.gov.br/?q=noticia&id=37167",
    contact: null,
    lastUpdate: "2024-03-01",
  },
  {
    id: 7,
    name: "SAMU 192",
    institution: "Ministério da Saúde",
    area: "Saúde",
    type: "Resposta",
    description:
      "Serviço de Atendimento Móvel de Urgência para emergências médicas.",
    location: "Nacional",
    url: "http://www.saude.gov.br/servicos/samu",
    contact: null,
    lastUpdate: "2024-03-05",
  },
  {
    id: 8,
    name: "Sistema de Alerta de Cheias",
    institution: "CPRM",
    area: "Hidrometeorológica",
    type: "Alerta",
    description:
      "Sistema de alerta de cheias para bacias hidrográficas brasileiras.",
    location: "Nacional",
    url: "https://www.cprm.gov.br/publique/Cheias/",
    contact: null,
    lastUpdate: "2024-03-10",
  },
  {
    id: 9,
    name: "Monitoramento de Deslizamentos",
    institution: "IPT",
    area: "Geológica",
    type: "Monitoramento",
    description:
      "Monitoramento de áreas de risco de deslizamento em São Paulo.",
    location: "São Paulo",
    url: "https://www.ipt.br/",
    contact: null,
    lastUpdate: "2024-03-15",
  },
  {
    id: 10,
    name: "Brigadas Escolares",
    institution: "Corpo de Bombeiros",
    area: "Incêndios",
    type: "Prevenção",
    description:
      "Programa de formação de brigadas escolares de combate a incêndio.",
    location: "Nacional",
    url: "https://www.corpodebombeiros.sp.gov.br/",
    contact: null,
    lastUpdate: "2024-03-20",
  },
  {
    id: 11,
    name: "Sistema de Informações sobre Desastres",
    institution: "Ministério do Desenvolvimento Regional",
    area: "Tecnológica",
    type: "Monitoramento",
    description:
      "Plataforma de informações sobre desastres naturais no Brasil.",
    location: "Nacional",
    url: "https://www.gov.br/mdr/pt-br/assuntos/protecao-e-defesa-civil/sistemas",
    contact: null,
    lastUpdate: "2024-03-25",
  },
  {
    id: 12,
    name: "Defesa Civil nas Escolas",
    institution: "Secretaria Nacional de Proteção e Defesa Civil",
    area: "Educação",
    type: "Educação",
    description:
      "Programa de educação sobre prevenção de desastres nas escolas.",
    location: "Nacional",
    url: "https://www.gov.br/mdr/pt-br/assuntos/protecao-e-defesa-civil/defesa-civil-na-escola",
    contact: null,
    lastUpdate: "2024-03-30",
  },
];

// Pontos de apoio para emergências
const supportPoints = [
  {
    id: 1,
    name: "Centro de Emergência São Paulo",
    type: "Defesa Civil",
    status: "Ativo",
    address: "Rua Líbero Badaró, 425 - Centro, São Paulo - SP",
    phone: "(11) 3397-8500",
    description:
      "Centro de coordenação de emergências da Defesa Civil de São Paulo",
    capacity: null,
  },
  {
    id: 2,
    name: "Abrigo Temporário Vila Madalena",
    type: "Abrigo",
    status: "Ativo",
    address: "Rua Harmonia, 1234 - Vila Madalena, São Paulo - SP",
    phone: "(11) 3456-7890",
    description: "Abrigo temporário para vítimas de desastres naturais",
    capacity: 200,
  },
  {
    id: 3,
    name: "Hospital de Emergência Rio",
    type: "Hospital",
    status: "Ativo",
    address: "Av. Brasil, 4365 - Manguinhos, Rio de Janeiro - RJ",
    phone: "(21) 2334-5678",
    description: "Hospital especializado em atendimento de emergências",
    capacity: null,
  },
  {
    id: 4,
    name: "Centro de Distribuição Belo Horizonte",
    type: "Distribuição",
    status: "Ativo",
    address: "Av. Afonso Pena, 1212 - Centro, Belo Horizonte - MG",
    phone: "(31) 3274-5555",
    description: "Centro de distribuição de suprimentos e doações",
    capacity: null,
  },
  {
    id: 5,
    name: "Quartel Bombeiros Porto Alegre",
    type: "Bombeiros",
    status: "Ativo",
    address: "Rua Voluntários da Pátria, 1358 - Centro, Porto Alegre - RS",
    phone: "(51) 3288-1234",
    description: "Quartel central dos Bombeiros de Porto Alegre",
    capacity: null,
  },
  {
    id: 6,
    name: "Abrigo Emergencial Florianópolis",
    type: "Abrigo",
    status: "Lotado",
    address: "Rua Felipe Schmidt, 515 - Centro, Florianópolis - SC",
    phone: "(48) 3212-3456",
    description: "Abrigo para situações de emergência climatológica",
    capacity: 150,
  },
  {
    id: 7,
    name: "Hospital Municipal de Trauma",
    type: "Hospital",
    status: "Emergência",
    address: "Av. Paulista, 2001 - Bela Vista, São Paulo - SP",
    phone: "(11) 3123-4567",
    description: "Hospital municipal especializado em trauma e emergências",
    capacity: null,
  },
  {
    id: 8,
    name: "Centro de Triagem Brasília",
    type: "Distribuição",
    status: "Ativo",
    address: "Esplanada dos Ministérios, Bloco A - Brasília - DF",
    phone: "(61) 3445-6789",
    description: "Centro nacional de triagem e distribuição de recursos",
    capacity: null,
  },
  {
    id: 9,
    name: "Defesa Civil Salvador",
    type: "Defesa Civil",
    status: "Ativo",
    address: "Rua Chile, 23 - Pelourinho, Salvador - BA",
    phone: "(71) 3116-7890",
    description: "Sede da Defesa Civil de Salvador",
    capacity: null,
  },
  {
    id: 10,
    name: "Abrigo Comunitário Recife",
    type: "Abrigo",
    status: "Ativo",
    address: "Rua do Bom Jesus, 163 - Recife Antigo, Recife - PE",
    phone: "(81) 3224-5678",
    description: "Abrigo comunitário para emergências urbanas",
    capacity: 100,
  },
];

// Voluntários (dados de exemplo para demonstração)
const volunteers = [
  {
    id: 1,
    name: "Maria Silva",
    location: "São Paulo, SP",
    skills: ["Primeiros Socorros", "Coordenação", "Comunicação"],
    availability: "Fins de semana",
    experience: "intermediaria",
    areas: ["Saúde", "Educação"],
  },
  {
    id: 2,
    name: "João Santos",
    location: "Rio de Janeiro, RJ",
    skills: ["Tecnologia", "Análise de Dados", "Programação"],
    availability: "Noites",
    experience: "avancada",
    areas: ["Tecnológica", "Monitoramento"],
  },
];

// Disponibilidades para voluntários
const availabilityOptions = [
  "Manhãs",
  "Tardes",
  "Noites",
  "Fins de semana",
  "Dias úteis",
  "Tempo integral",
  "Conforme necessário",
];

// Áreas de interesse para voluntários
const volunteerAreas = [
  {
    value: "hidro",
    label: "Eventos Hidrometeorológicos",
    description: "Chuvas, enchentes, secas",
  },
  {
    value: "geo",
    label: "Eventos Geológicos",
    description: "Deslizamentos, terremotos",
  },
  {
    value: "fire",
    label: "Incêndios",
    description: "Prevenção e combate a incêndios",
  },
  {
    value: "tech",
    label: "Tecnologia",
    description: "Desenvolvimento e suporte técnico",
  },
  {
    value: "health",
    label: "Saúde",
    description: "Primeiros socorros e assistência médica",
  },
  {
    value: "edu",
    label: "Educação",
    description: "Conscientização e treinamento",
  },
  {
    value: "logistics",
    label: "Logística",
    description: "Distribuição e coordenação",
  },
  {
    value: "communication",
    label: "Comunicação",
    description: "Alertas e divulgação",
  },
];

console.log("📊 Dados carregados:", {
  projetos: projects.length,
  pontosApoio: supportPoints.length,
  voluntarios: volunteers.length,
});
